apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  externalIPs:
  - 172.28.4.4
  selector: 
    app: alertmanager  
  ports:
    - port: 9093
      targetPort: 9093
