apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  externalIPs:
  - 172.28.4.4
  selector: 
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
