apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'  
spec:
  externalIPs:
  - 172.28.4.4
  selector: 
    app: prometheus-server 
  ports:
   - name: http
     protocol: TCP
     port: 9090
     targetPort: 9090
